//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int id_producto { get; set; }
        public int id_unidad_medida { get; set; }
        public int id_subcategoria { get; set; }
        public string nombre_producto { get; set; }
        public string precio_producto { get; set; }
        public string descripcion_producto { get; set; }
        public int stock { get; set; }
    
        public virtual subcategoria subcategoria { get; set; }
        public virtual unidad_medida unidad_medida { get; set; }
    }
}
